In [1]:
from collections import abc
issubclass(tuple, abc.Sequence)

True

In [3]:
issubclass(list, abc.MutableSequence)

True

In [4]:
symbols = '$¢£¥€¤'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))

codes


[36, 162, 163, 165, 8364, 164]

In [5]:
codes = [ord(symbol) for symbol in symbols] #listcomp
codes

[36, 162, 163, 165, 8364, 164]

In [6]:
x = 'ABC'
codes = [ord(x) for x in x]
x

'ABC'

In [7]:
codes

[65, 66, 67]

In [9]:
codes = [last:= ord(c) for c in x]
last

67

In [10]:
c

NameError: name 'c' is not defined

In [11]:
symbols = '$¢£¥€¤'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127] #faster 
beyond_ascii

[162, 163, 165, 8364, 164]

In [12]:
beyond_ascii = list(filter(lambda c: c > 127, map(ord, symbols)))
beyond_ascii

[162, 163, 165, 8364, 164]

In [13]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [14]:
for color in colors:
    for size in sizes:
        print((color, size))

('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [16]:
tshirts = [(color, size) for size in sizes for color in colors]
tshirts

[('black', 'S'),
 ('white', 'S'),
 ('black', 'M'),
 ('white', 'M'),
 ('black', 'L'),
 ('white', 'L')]

In [17]:
tuple(ord(symbol) for symbol in symbols)

(36, 162, 163, 165, 8364, 164)

In [18]:
import array
array.array('I', (ord(symbol) for symbol in symbols))

array('I', [36, 162, 163, 165, 8364, 164])

In [20]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
for tshirt in (f'{c} {s}' for c in colors for s in sizes):
    print(tshirt)

black S
black M
black L
white S
white M
white L


In [37]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32_450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'),
    ('ESP', 'XDA205856')]
for passport in sorted(traveler_ids):
    print( '%s/%s' % passport)



BRA/CE342567
ESP/XDA205856
USA/31195855


In [22]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


In [23]:
a = (10, 'alpha',[1,2])
b = (10, 'alpha', [1,2])
a == b

True

In [24]:
b[-1].append(99)
a == b

False

In [25]:
b 

(10, 'alpha', [1, 2, 99])

In [30]:
def fixed(o):
    try:
        hash(o)
    except TypeError:
        return False
    return True

tf = (10, 'alpha', (1, 2))

In [31]:
tn = (10, 'alpha', [1,2])
fixed(tf)

True

In [32]:
fixed(tn)

False

In [36]:
#Unpacking Sequences and Iterables
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
latitude

33.9425

In [38]:
longitude

-118.408056

In [39]:
b, a = a, b

In [40]:
divmod(20, 8)

(2, 4)

In [41]:
t = (20, 8)
divmod(*t)

(2, 4)

In [42]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [43]:
import os
_, filename =os.path.split('/home/luciano/.ssh/id_rsa.pub')

In [44]:
filename

'id_rsa.pub'

In [46]:
a, b, *rest = range(5)
a,b , rest

(0, 1, [2, 3, 4])

In [47]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [50]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [51]:
a, *body, c, d =  range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [52]:
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

In [53]:
def fun(a, b, c, d, *rest):
    return a, b, c, d, rest

In [54]:
fun (*[1,2], 3, *range(4,7))

(1, 2, 3, 4, (5, 6))

In [55]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),  
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('São Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]

def main():
    print(f'{"":15} | {"latitude":>9} | {"longitude":>9}')
    for name, _, _, (lat, lon) in metro_areas:
        if lon <=0:
            print(f'{name:<15} {lat:>9} {lon:>9}')
if __name__ == '__main__':
    main()

                |  latitude | longitude
Mexico City     19.433333 -99.133333
New York-Newark 40.808611 -74.020386
São Paulo       -23.547778 -46.635833


In [ ]:
#Pattern Matching

def handle_command(self, message):
    match message: #subject
        case ['BEEPER', frequency, times]:
            self.beep(times, frequency)
        case ['NECK', angle]:
            self.rotate_neck(angle)
        case ['LED', ident, intensity]:  
            self.leds[ident].set_brightness(ident, intensity)
        case ['LED', ident, red, green, blue]:  
            self.leds[ident].set_color(ident, red, green, blue)
        case _:  
            return

In [56]:
def main():
    print(f'{"":15} | {"latitude":>9} | {"longitude":>9}')
    for record in metro_areas:
        match record: #match record
            case [name, _, _, (lat, lon)] if lon <= 0: #case clause has two parts
                print(f'{name:<15} {lat:>9} {lon:>9}')

In [58]:
#Slicing
#.__getitem__(slice(start, stop, step))

l = [10, 20, 30, 40, 50, 60]
l[:2]

[10, 20]

In [59]:
l[2:]

[30, 40, 50, 60]

In [60]:
l[:3]

[10, 20, 30]

In [61]:
l[3:]

[40, 50, 60]

In [63]:
s = 'bicycle'
s[::3]

'bye'

In [64]:
s[::-1]

'elcycib'

In [65]:
s[::-2]

'eccb'

In [68]:
invoice = """
0.....6.................................40........52...55........
1909  Pimoroni PiBrella                     $17.50    3    $52.50
1489  6mm Tactile Switch x20                 $4.95    2     $9.90
1510  Panavise Jr. - PV-201                 $28.00    1    $28.00
1601  PiTFT Mini Kit 320x240                $34.95    1    $34.95
"""

SKU = slice(0,6)
DESCRIPTION = slice(6,40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)
line_items = invoice.split('\n')[2:]
for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

    $17.50   Pimoroni PiBrella                 
     $4.95   6mm Tactile Switch x20            
    $28.00   Panavise Jr. - PV-201             
    $34.95   PiTFT Mini Kit 320x240            
 


In [75]:
#Assigning to slices

l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [76]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [77]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [78]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [82]:
l[2:5] = [100,]
l

[0, 1, 100]

In [83]:
#Using + and * with Sequences
l = [1,2,3]
l*5


[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [84]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

In [86]:
#Building lists of lists

board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [87]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [88]:
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [90]:
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [91]:
#Augmented assignment with Sequences
l = [1,2,3]
id(l)

4634005376

In [92]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [93]:
id(l)

4634005376

In [94]:
t = (1, 2, 3)
id(t)

4633882048

In [95]:
t *= 2
id(t) #new tuple created

4634616992

In [96]:
# A+= Assignment Puzzler
t = (1,2, [30,40])
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [97]:
t

(1, 2, [30, 40, 50, 60])

In [105]:
#list.sort Versus the sorted Built-In
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [99]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [100]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [101]:
sorted(fruits, key=len, reverse= True)

['raspberry', 'banana', 'grape', 'apple']

In [106]:
fruits #ordering is still preserved

['grape', 'raspberry', 'apple', 'banana']

In [103]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

In [108]:
#Arrays
from array import array
from random import random


floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.9955887571284645

In [109]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()
floats2[-1]

0.9955887571284645

In [110]:
floats2 == floats

True

In [111]:
#Memory Views
#Share memory between data structures without first copying

octets = array('B', range(6))
m1 = memoryview(octets)
m1.tolist()

[0, 1, 2, 3, 4, 5]

In [112]:
m2 = m1.cast('B', [2,3])
m2.tolist()

[[0, 1, 2], [3, 4, 5]]

In [114]:
m3 = m1.cast('B', [3,2])
m3.tolist()

[[0, 1], [2, 3], [4, 5]]

In [115]:
m2[1,1] = 22
m3[1,1] = 33
octets

array('B', [0, 1, 2, 33, 22, 5])

In [116]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [117]:
type(a)

numpy.ndarray

In [118]:
a.shape

(12,)

In [121]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
a[2]

array([ 8,  9, 10, 11])

In [123]:
a[2,1]

np.int64(9)

In [124]:
a[:, 1] #Get column at index 1

array([1, 5, 9])

In [125]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [127]:
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [128]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)

In [130]:
dq.rotate(-4)
dq

deque([5, 6, 7, 8, 9, 0, 1, 2, 3, 4], maxlen=10)

In [132]:
dq.appendleft(-1)
dq

deque([-1, -1, 5, 6, 7, 8, 9, 0, 1, 2], maxlen=10)

In [133]:
dq.extend([11,22,33])
dq

deque([6, 7, 8, 9, 0, 1, 2, 11, 22, 33], maxlen=10)

In [134]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 6, 7, 8, 9, 0, 1], maxlen=10)